
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int MOD = 9;
  public static final int AND = 19;
  public static final int LT = 16;
  public static final int NOTEQ = 17;
  public static final int PLUS = 4;
  public static final int OR = 20;
  public static final int RPAREN = 11;
  public static final int SEMI = 3;
  public static final int NOT = 18;
  public static final int IDENTIFIER = 23;
  public static final int LPAREN = 10;
  public static final int GT = 15;
  public static final int STRING = 22;
  public static final int COMMA = 2;
  public static final int LTEQ = 14;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int GTEQ = 13;
  public static final int EQEQ = 12;
  public static final int UMINUS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "LPAREN",
  "RPAREN",
  "EQEQ",
  "GTEQ",
  "LTEQ",
  "GT",
  "LT",
  "NOTEQ",
  "NOT",
  "AND",
  "OR",
  "NUMBER",
  "STRING",
  "IDENTIFIER"
  };
}

